_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": darwin-arm64
