level = [
"WWWWWWWWWWWWWWWWWWWWWWWWW",
"W                       W",
"W            W          W",
"W            W          W",
"W      WWWWWWWWWWW      W",
"W             W         W",
"W             W         W",
"W                       W",
"WWWWWW                  W",
"W                       W",
"W                       W",
"W               W       W",
"W               W       W",
"W               W       W",
"W               W       W",
"W        WWWWWWWW       W",
"W        W              W",
"W        W              W",
"W        W              W",
"W                       W",
"W                       W",
"W             WWWWWW    W",
"W                W      W",
"W                W      W",
"WWWWWWWWWWWWWWWWWWWWWWWWW",
]
